DATA_PREFIX_PATH="/home/ishikaa2/thermostat"


export CUDA_VISIBLE_DEVICES
MODEL_PATH='Qwen/Qwen2.5-0.5B'
MODEL_NICKNAME="qwen0.5b"
DATA_DIR=${DATA_PREFIX_PATH}'/data/aime2024.json'
TRAINING_DATA_NAME=aime
export GLOBAL_LANGUAGE_MODEL_NAME=$MODEL_PATH
TARGET_TASK_NAMES=$TRAINING_DATA_NAME
TASK=$DATA_DIR
source less.sh
